language: csharp
solution: Gateway.sln
notifications:
  email:
    on_success: always
    on_failure: always
  slack: srboeingdotnet:GhCzs3W4Gj7eaQ2pLNwIWVCa
mono: none
dotnet: 2.1
script:
  - dotnet restore Gateway/
after_success:
  - /bin/bash ./deploy.sh  