version: '3'
services:
  gateway:
    build:
      context: ./Gateway
    network_mode: host
    depends_on:
      - consul
      - registrator
  consul:
    image: consul
    restart: always
    ports:
      - "0.0.0.0:8500:8500"
  registrator:
    image: gliderlabs/registrator
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://localhost:8500