version: '3.4'

services:
  db:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "YourStrongP@ssword"
      ACCEPT_EULA: "Y"

  dbb:
    image: mongo
    ports:
      - "27017:27017"

  servicea:
    image: questionbank
    build:
      context: ./QuestionBank/Admin/Admin
      dockerfile: Dockerfile
    depends_on:
      - dbb

  serviceb:
    image: userlogin
    build:
      context: ./UserLogin/UserLoginAPI/UserLoginAPI
      dockerfile: Dockerfile
    depends_on:
      - db

  servicec:
    image: result
    build:
      context: ./Result/Result/Result
      dockerfile: Dockerfile
    depends_on:
      - dbb

  gateway:
    image: gateway
    build:
      context: ./Gateway
      dockerfile: Dockerfile
